[package]
name = "code-workspaces-cleaner-upper"
version = "1.0.0"
edition = "2021"

[dependencies]
# This version is so clap_derive works ig
clap = {version = "4.5", features = ["derive"]}
fs_extra = "1.3"
humansize = "2.1"
walkdir = "2.5"
